name: Build HyperOS Watchface

on:
  push:
    paths:
      - 'input.zip'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Unpack and Compile
        run: |
          Expand-Archive -Path input.zip -DestinationPath .\source -Force
          .\compile.exe .\source
          Get-ChildItem -Path . -Filter *.bin -Recurse | Copy-Item -Destination .\result.bin

      - name: Save Compiled BIN
        uses: actions/upload-artifact@v4
        with:
          name: watchface-bin
          path: result
          .bin
