name: Build Watchface

on:
  push:
    paths:
      - 'input.zip'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          Expand-Archive -Path input.zip -DestinationPath .\source -Force
          .\compile.exe .\source
          Get-ChildItem -Path . -Filter *.bin -Recurse | Select-Object -First 1 | Copy-Item -Destination .\result.bin

      - uses: actions/upload-artifact@v4
        with:
          name: watchface-bin
          path: result.bin
